services:
  - name: backend
    type: web
    runtime: docker
    buildCommand: docker build -t fena-backend -f src/backend/Dockerfile .
    envVars:
      - key: FRONTEND_URL
        value: http://localhost:3001
      - key: SESSION_SECRET
        value: secret
      - key: REDIS_HOST
        value: localhost
      - key: REDIS_PORT
        value: 6379
    healthCheckPath: "/"
  - name: frontend
    type: web
    runtime: docker
    buildCommand: docker build -t fena-frontend -f src/frontend/Dockerfile .
    envVars:
      - key: PORT
        value: 3001
      - key: REACT_APP_BACKEND_HOST
        value: localhost
      - key: REACT_APP_BACKEND_PORT
        value: 3000
      - key: REACT_APP_BACKEND_PREFIX
        value: "/api"
    healthCheckPath: "/"
  - name: redis
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    type: redis